### ISSUE TITLE
Create a pypi release

### ISSUE THREAD

**Issue by slinkymanbyday** [telstra/MessagingAPI-SDK-python#4]
Would love for this to be on https://pypi.org
at the moment, everytime i deploy, pip does a git clone and builds this module, while all the other modules are versioned and doesn't have to redownload everytime.

**Comment by developersteve** [comment]
Hi @slinkymanbyday, 

Ive just pushed to pypi, give this one a try https://pypi.org/project/Telstra-Messaging/1.0.6/

**Comment by slinkymanbyday** [comment]
legend, thankyou!
